### ISSUE TITLE
Homebrew formula?

### ISSUE THREAD

**Issue by ylluminarious** [kerma/defaultbrowser#13]
This utility is useful. It would be nice to have convenient installation of it through [homebrew.](https://brew.sh/) A formula should be quite easy to write.

**Comment by kerma** [comment]
I’d be happy to include one. I haven’t written one myself before, so PR would be sweet. I can take a stab at it myself 3-4 weeks from now.

**Comment by ylluminarious** [comment]
@kerma [I created a PR to homebrew-core.](https://github.com/Homebrew/homebrew-core/pull/23621)

**Comment by kerma** [comment]
@ylluminarious thanks!
