### ISSUE TITLE
'make install' should create $(PREFIX)/bin

### ISSUE THREAD

**Issue by ylluminarious** [kerma/defaultbrowser#14]
The `make install` target for this program does not ensure that the `bin` directory which it installs to is actually there. This led to [a complaint](https://github.com/Homebrew/homebrew-core/pull/23621#discussion_r166582021) from a homebrew maintainer, saying that this should be fixed here. It should be as simple as adding this:

```make
install:
	mkdir -p $(PREFIX)/bin # add this
	cp $(BIN) $(PREFIX)/bin/
```

**Comment by DomT4** [comment]
Something like https://github.com/kerma/defaultbrowser/pull/15 does the job.
