### ISSUE TITLE
Integrated Google Chrome Incognito

### ISSUE THREAD

**Issue by aletheia7** [kerma/defaultbrowser#18]
I use [Google Chrome Incognito](https://apple.stackexchange.com/questions/25375/how-do-i-open-google-chrome-in-incognito-mode-by-default). [Description Link](https://apple.stackexchange.com/questions/25375/how-do-i-open-google-chrome-in-incognito-mode-by-default).

It is a small compiled binary that executes an applescript to open Google Chrome in incognito mode. Any pointers on how I can integrate ```defaultbrowser``` to run the Google Chrome Incognito.app? ```defaultbrowser``` does not see Google Chrome Incognito.app in the listing.

Thank you.

**Comment by kerma** [comment]
`defaultbrowser` relies on [LSCopyAllHandlersForURLScheme](https://developer.apple.com/documentation/coreservices/1443240-lscopyallhandlersforurlscheme?language=objc). 

According to the docs the problem seems to be on your binary side:

> URL handling capability is determined according to the value of the [CFBundleURLTypes](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102207) key in an application’s Info.plist.

You probably need to make the binary to be a "real mac app" with it's `Info.plist`.

**Comment by aletheia7** [comment]
> `defaultbrowser` relies on [LSCopyAllHandlersForURLScheme](https://developer.apple.com/documentation/coreservices/1443240-lscopyallhandlersforurlscheme?language=objc).
> 
> According to the docs the problem seems to be on your binary side:
> 
> > URL handling capability is determined according to the value of the [CFBundleURLTypes](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102207) key in an application’s Info.plist.
> 
> You probably need to make the binary to be a "real mac app" with it's `Info.plist`.

Thank you for your help. The developer of Google Chrome Incognito.app enhanced the app to work with CFBundleURLTypes.

New Version: [Google Chrome Incognito](https://ente.limmat.ch/ftp/pub/software/applications/GoogleChromeIncognito/)
