### ISSUE TITLE
New browser 'Arc'

### ISSUE THREAD

**Issue by vjonas** [kerma/defaultbrowser#24]
Hey

Is it possible for the script to detect the new browser 'arc' too?
I notice it does not recognise it in the returned list.

I get these ones;
``` 
iterm2
  chrome
* safari
  b99b77c39738484f8a5516125745b0d7
  browser
  torbrowser
  console
  firefox
```

Kind regards

Jonas

**Comment by kevinbarrionuevo** [comment]
Hello,

I'm also using Arc, and it's listed as 'browser'

```
  safari
  browser
  safaritechnologypreview
```

When I run `defaultbrowser browser`, I get the following modal:

![Capture d’écran 2023-08-29 à 08 30 28](https://github.com/kerma/defaultbrowser/assets/3474578/db190247-7b5c-407b-bf8d-4e08921e39fd)

Kind Regards,
Kevin

**Comment by vjonas** [comment]
Thanks for the reply!
I noticed that is uses the same name as the brave browser.
I removed Brave browser and then it seemed to work! Seems like there is a conflict in there.

**Comment by kevinbarrionuevo** [comment]
It seems that Brave and Arc are using the same name in their bundle identifiers; the conflict may come from here. This script uses only the last component of the string to get the browser's name.

```
<string>com.brave.Browser</string>

<string>company.thebrowser.Browser</string>
```

There is still an open issue in the Brave repo: https://github.com/brave/brave-browser/issues/3759
