### ISSUE TITLE
Distribution of your program in an Alfred workflow

### ISSUE THREAD

**Issue by stuartcryan** [kerma/defaultbrowser#4]
Hi Margus,
I am putting together an Alfred workflow that I would like to use your defaultbrowser program in. The simplest method to put this together is to include the binary in with the Alfred workflow rather than writing a series of scripts to try to download it/put it in the right location etc etc.

Would you please permit me to create an Alfred Workflow (http://alfredapp.com) providing that I put the attribution to yourself in the README files for the workflow detailing the supporting program you have written?

Many thanks
Stuart

**Comment by kerma** [comment]
Hi Stuart,

Yes please, go ahead. I'm an avid Alfred user as well. 

Cheers,
Margus

**Comment by stuartcryan** [comment]
Thanks so much :) I will prep a new version of the workflow (that is a little better than the thrown together versions) and keep you posted.
