### ISSUE TITLE
Support FirefoxDeveloperEdition

### ISSUE THREAD

**Issue by wavded** [kerma/defaultbrowser#6]
Would love to have this browser supported!  Haven't tested it but also Webkit nightlies too!

Thanks for the extension.

**Comment by stuartcryan** [comment]
Hi Wavded, not that I maintain defaultbrowser, but what doesn't seem to work for FirefoxDeveloperEdition? I have tried it with my most recent fork and it appears to work just fine?
Cheers,
Stuart

**Comment by wavded** [comment]
@stuartcryan hmm, not sure what I'm doing wrong then.  I'm typing `db d` or `db f` in Alfred and neither show up, just chrome and safari ATM.  any ideas?

**Comment by wavded** [comment]
@stuartcryan looks like the command line tool shows all the available browsers, just not the Alfred workflow.

**Comment by stuartcryan** [comment]
Ahh I thought you might have meant in the alfred workflow. I have created a ticket in the Workflow github tracker (as it is to do with my code, not Kerma's).

This can be closed and I will get you the updated version shortly.
Cheers,
Stuart

**Comment by stuartcryan** [comment]
And @wavded please see https://github.com/stuartcryan/defaultbrowser-alfred-workflow/issues/9 as I have released the updated code for you.
Cheers,
Stuart

**Comment by wavded** [comment]
Thanks @stuartcryan , works now!
