### ISSUE TITLE
List of available options

### ISSUE THREAD

**Issue by elia** [kerma/defaultbrowser#7]
I'd like to have a CLI option to show the list of available choices

**Comment by stuartcryan** [comment]
Hi Elia, I actually did this for my own purposes for an Alfred workflow to control the default browser. I made a pull request a little over a year ago, however, the pull request is still open.

Still works to this day --> https://github.com/kerma/defaultbrowser/pull/5

The binary is available in https://github.com/stuartcryan/defaultbrowser-alfred-workflow/tree/master/workflow if you would like.

**Comment by elia** [comment]
Thanks, I ended up passing a bogus argument and getting the list in response. 

Sill think it's a valuable feature for the main project, so 👍🏻 For the PR!

**Comment by specious** [comment]
One of the changes in #12 is listing available choices by default.

**Comment by kerma** [comment]
Solved in #12
